### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [peercoin/peercoin_flutter#118]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 13 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Peercoin_flutter (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Peercoin_flutter's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by bananenwilly** [comment]
thanks for reaching out. You can reach me at willy@app.peercoin.net

**Comment by misterAnderson90** [comment]
@willyfromtheblock ,

Did you receive the gists? I have shared them with you by email. Please let me know if you need me to share with you again.

**Comment by willyfromtheblock** [comment]
@misterAnderson90 I have, thank you. 
I saw that three of them are from flutter_secure_storage, one is on google domain, the other on androidx.
We're looking into it

**Comment by MatthewLM** [comment]
@misterAnderson90 Thank you for these reports. I've taken a look and I cannot find any vulnerabilities concerning the dependencies in question. These results appear to be false positives or are not relevant to the latest package versions. I've commented on the 5 gists forwarded to me. If there are any further considerations, I'll be happy to take a further look.
