### ISSUE TITLE
Not able to create new wallet on iPhone.

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin_flutter#129]
A friend tried to create a new wallet on iPhone. The spinning circle would not stop spinning and no wallet was created. He tried to uninstall the app and try again, but that did not work. Peercoin_flutter v0.8.1

**Comment by bananenwilly** [comment]
https://github.com/peercoin/peercoin_flutter/pull/128/commits/dbd8c8b32a07acf8b8d40774caace068e71af535
https://github.com/mogol/flutter_secure_storage/issues/338

Will be fixed with 0.8.2 today. Thanks for reporting.
