### ISSUE TITLE
Add more languages from countries with high adoption of crypto and a large population

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin_flutter#133]
I think we should add these languages as well since adoption of crypto is high in these countries and they have a large population:

Kenya - Swahili (sw)
Nigeria - Hausa (ha)
Pakistan - Urdu (ur)
Ukraine - Ukrainian (uk)
Vietnam - Vietnamese (vi)

https://www.statista.com/chart/26757/cryptocurrency-adoption-world-map

**Comment by bananenwilly** [comment]
All requested.
