### ISSUE TITLE
The exchange rate for Argentine peso (ARS) is not correct

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin_flutter#134]
The exchange rate for Argentine peso (ARS) is not correct from this API: https://peercoinexplorer.net/price-ticker

https://github.com/Electron-Cash/Electron-Cash/pull/2326

https://github.com/Electron-Cash/Electron-Cash/issues/2283

**Comment by bananenwilly** [comment]
![Screenshot_20220210-081244_Firefox](https://user-images.githubusercontent.com/11148913/153356271-1f2912e5-015d-4593-b98e-881fc623f889.jpg)

Ticker:
 "ARS": 105.866435, 

You want to use some "unofficial" source?

**Comment by sandakersmann** [comment]
Yes, because the official rate is just BS from the government in Argentina. People on the ground there does not use that rate.
