### ISSUE TITLE
Sign / verify message

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin_flutter#15]
Mirror the sign/verify message functionality from peercoin-qt.

![image](https://user-images.githubusercontent.com/7818961/112630554-06e54900-8e36-11eb-9322-cb2da0c7d0e6.png)

![image](https://user-images.githubusercontent.com/7818961/112630581-119fde00-8e36-11eb-96c0-83635eee09c3.png)

**Comment by bananenwilly** [comment]
not sure this is supported by the underlying plugin as of now.

**Comment by willyfromtheblock** [comment]
verifying is still awaiting implementation in coinslib
