### ISSUE TITLE
Import paper wallet does not work on v0.8.9

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin_flutter#154]
Import paper wallet does not work on v0.8.9. The process seems to run fine, but no funds are swept.

**Comment by willyfromtheblock** [comment]
I have just successfully imported from my test paper wallet:
https://tblockbook.peercoin.net/tx/ca38372201509807a48c49aa76ec096820f1961619f3aa528c361801617fa654

Please provide debug logs to troubleshoot this. If you don't want to share them here, you know how to reach me on Telegram.

**Comment by willyfromtheblock** [comment]
fixed with #155  according to @sandakersmann
