### ISSUE TITLE
"Minimum output is $amount" message not interpolated correctly.

### ISSUE THREAD

**Issue by ihavenoface** [peercoin/peercoin_flutter#157]
![IMG_0591](https://user-images.githubusercontent.com/1175752/165316587-2e43250b-97f1-4b90-9cae-0a044ad37b97.PNG)

**Comment by willyfromtheblock** [comment]
fixed with https://github.com/peercoin/peercoin_flutter/commit/c3afc60708d2c3ecc22ffdfcff6913b38d933fcc 
coming with 0.9.1
