### ISSUE TITLE
Scanning of QR codes does not work on v0.9.4

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin_flutter#166]
Scanning of QR code does not work on v0.9.4. The camera does not turn on and the background stays black.

**Comment by willyfromtheblock** [comment]
That is android or iOS? I need device details.

**Comment by willyfromtheblock** [comment]
I managed to reproduce on Android 10. 
Camera will only work exactly once, right after granting permissions. Using it again leads to the behavior you described.

Can you confirm this is Android 10?
The underlying changes already happened in 0.9.3, can you confirm that didn't work as well?
Can you try revoking camera access in app info and trying again? It should work exactly once and I think it is this issue then:

https://github.com/juliuscanute/qr_code_scanner/issues/550

**Comment by sandakersmann** [comment]
I'm on Samsung Galaxy S10+ with Android 12. I don't know if v0.9.3 didn't work as well.

**Comment by sandakersmann** [comment]
"Can you try revoking camera access in app info and trying again? It should work exactly once"

Confirmed

**Comment by willyfromtheblock** [comment]
fixed with https://github.com/peercoin/peercoin_flutter/commit/ddf49a0b48ce0b6677f1e40f8369b104a274f6da
