### ISSUE TITLE
Add more fiat currencies

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin_flutter#232]
We should add these also:

AFN
ANG
AWG
BBD
BMD
BZD
CUP
DJF
DZD
ERN
ETB
GHS
GIP
HTG
KHR
KPW
KYD
MMK
MRO
NIO
NPR
PAB
PKR
SBD
SHP
SOS
SRD
SSP
SVC
SYP
TMT
TOP
UZS
VEF
VUV
WST
XCD

That would give us this complete list:

AED
AFN
ALL
AMD
ANG
AOA
ARS
AUD
AWG
AZN
BAM
BBD
BDT
BGN
BHD
BIF
BMD
BND
BOB
BRL
BSD
BTN
BWP
BYN
BZD
CAD
CDF
CHF
CLP
CNY
COP
CRC
CUP
CVE
CZK
DJF
DKK
DOP
DZD
EGP
ERN
ETB
EUR
FJD
GBP
GEL
GHS
GIP
GMD
GNF
GTQ
GYD
HKD
HNL
HTG
HUF
IDR
ILS
INR
IQD
IRR
ISK
JMD
JOD
JPY
KES
KGS
KHR
KMF
KPW
KRW
KWD
KYD
KZT
LAK
LBP
LKR
LRD
LSL
LYD
MAD
MDL
MGA
MKD
MMK
MNT
MOP
MRO
MUR
MVR
MWK
MXN
MYR
MZN
NAD
NGN
NIO
NOK
NPR
NZD
OMR
PAB
PEN
PGK
PHP
PKR
PLN
PPC
PYG
QAR
RON
RSD
RUB
RWF
SAR
SBD
SCR
SDG
SEK
SGD
SHP
SLL
SOS
SRD
SSP
STD
SVC
SYP
SZL
THB
TJS
TMT
TND
TOP
TRY
TTD
TWD
TZS
UAH
UGX
UYU
UZS
VEF
VND
VUV
WST
XAF
XCD
XOF
XPF
ZAR
ZMK

**Comment by willyfromtheblock** [comment]
PKR was already in the list.

https://github.com/willyfromtheblock/ppc-worker-price-update/commit/02c3e3cac6fc7b9381f2942f3758af313ee941cb
https://github.com/peercoin/peercoin_flutter/commit/ec8ed343f47d4d6f5d99b2622c8f17c19b10813f
https://github.com/peercoin/peercoin_flutter/commit/8ae982eaa0c5e4a82cf45df3b7c9de058bc18563
