### ISSUE TITLE
Op return field in the send tab

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin_flutter#3]
Send tab allows for amount and destination field so far. It would benefit some use cases should it offer a 'Metadata' field, ie op_return. This field should be hidden by default but in settings there should be an option which makes it visible.

**Comment by lorenz10-forker** [comment]
I tried to add support for OP_RETURN transactions on dart-bitcoin/bitcoin_flutter few weeks ago, I hope they are going to merge it...

https://github.com/dart-bitcoin/bitcoin_flutter/pull/56

**Comment by peerchemist** [comment]
It's a relatively easy patch, we can actually already pick it up.

**Comment by lorenz10-forker** [comment]
Yes it is really trivial. 
Do you think that someone should be allowed to perform OP_RETURN transactions alone or they must be always embedded with a monetary transaction? 
Also what is the max size of data that can be ambedded with OP_RETURN in Peercoin?

**Comment by peerchemist** [comment]
> Do you think that someone should be allowed to perform OP_RETURN transactions alone or they must be always embedded with a monetary transaction?

They should be free to do whatever they want.

>  Also what is the max size of data that can be ambedded with OP_RETURN in Peercoin?

256 byte

**Comment by peerchemist** [comment]
> I tried to add support for OP_RETURN transactions on dart-bitcoin/bitcoin_flutter few weeks ago, I hope they are going to merge it...
> 
> [dart-bitcoin/bitcoin_flutter#56](https://github.com/dart-bitcoin/bitcoin_flutter/pull/56)

I see you are author of this PR. PR it against our fork please. We do not need to wait for the upstream.

https://github.com/Vesta-wallet/bitcoin_flutter

**Comment by lorenz10-forker** [comment]
> I see you are author of this PR. 
I thought that a pull in the top level would have been propagated through the forks. 

> PR it against our fork please. We do not need to wait for the upstream.
Ok

**Comment by bananenwilly** [comment]
solved with https://github.com/peercoin/peercoin_flutter/pull/111
