### ISSUE TITLE
Words correction

### ISSUE THREAD

**Issue by Vitalicus** [peercoin/peercoin_flutter#30]
https://github.com/peercoin/peercoin_flutter/blob/b2b39d35b59fb5cc30f73f4436af71e979ffc54d/assets/translations/en.json#L106

https://github.com/peercoin/peercoin_flutter/blob/b2b39d35b59fb5cc30f73f4436af71e979ffc54d/assets/translations/en.json#L108
succesfully > successfully

https://github.com/peercoin/peercoin_flutter/blob/b2b39d35b59fb5cc30f73f4436af71e979ffc54d/assets/translations/en.json#L59
authentification > authentication

**Comment by bananenwilly** [comment]
https://github.com/peercoin/peercoin_flutter/commit/08e52ce74864fa862bd01844451988235adfd464
https://github.com/peercoin/peercoin_flutter/commit/0e0e8c81c712648c5dc53f0334f8706237c65890

Thanks
