### ISSUE TITLE
Crash on Authentication

### ISSUE THREAD

**Issue by qstarx** [peercoin/peercoin_flutter#54]
On Android 8.0 app crashes as soon as the authentication dialog appears

**Comment by bananenwilly** [comment]
what device is this?

**Comment by qstarx** [comment]
Its a LG G6 (64 GB dual sim version)

**Comment by bananenwilly** [comment]
I've tried a fix with https://github.com/peercoin/peercoin_flutter/releases/tag/v0.3.7-alpha 

It should be live on the play store within one hour.

**Comment by bananenwilly** [comment]
Fixed with 0.3.7
